import { API } from "../utils/API";
import {
  GET_CHATS,
  START_CHAT,
  CREATE_GROUP,
  REMOVE_GROUP,
  ADD_TO_GROUP,
  REMOVE_FROM_GROUP,
  GET_CHAT_MESSAGES,
  ADD_LIKE,
  REMOVE_LIKE,
  SEND_MESSAGE
} from "../constants/ROUTES";

